// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ProxyCoreService.proto

package proxycoreproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreName      string                 `protobuf:"bytes,1,opt,name=coreName,proto3" json:"coreName,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	IsString      bool                   `protobuf:"varint,5,opt,name=isString,proto3" json:"isString,omitempty"`
	IsVpnMode     bool                   `protobuf:"varint,6,opt,name=isVpnMode,proto3" json:"isVpnMode,omitempty"`
	TunFD         uint32                 `protobuf:"varint,7,opt,name=tunFD,proto3" json:"tunFD,omitempty"`
	ProxyPort     int32                  `protobuf:"varint,8,opt,name=proxyPort,proto3" json:"proxyPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCoreRequest) Reset() {
	*x = StartCoreRequest{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCoreRequest) ProtoMessage() {}

func (x *StartCoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCoreRequest.ProtoReflect.Descriptor instead.
func (*StartCoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{0}
}

func (x *StartCoreRequest) GetCoreName() string {
	if x != nil {
		return x.CoreName
	}
	return ""
}

func (x *StartCoreRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *StartCoreRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCoreRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *StartCoreRequest) GetIsString() bool {
	if x != nil {
		return x.IsString
	}
	return false
}

func (x *StartCoreRequest) GetIsVpnMode() bool {
	if x != nil {
		return x.IsVpnMode
	}
	return false
}

func (x *StartCoreRequest) GetTunFD() uint32 {
	if x != nil {
		return x.TunFD
	}
	return 0
}

func (x *StartCoreRequest) GetProxyPort() int32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

type MeasurePingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []string               `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurePingRequest) Reset() {
	*x = MeasurePingRequest{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurePingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurePingRequest) ProtoMessage() {}

func (x *MeasurePingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurePingRequest.ProtoReflect.Descriptor instead.
func (*MeasurePingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{1}
}

func (x *MeasurePingRequest) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

type BooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       bool                   `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanResponse) Reset() {
	*x = BooleanResponse{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanResponse) ProtoMessage() {}

func (x *BooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanResponse.ProtoReflect.Descriptor instead.
func (*BooleanResponse) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{2}
}

func (x *BooleanResponse) GetMessage() bool {
	if x != nil {
		return x.Message
	}
	return false
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{4}
}

func (x *LogResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type MeasurePingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PingResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurePingResponse) Reset() {
	*x = MeasurePingResponse{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurePingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurePingResponse) ProtoMessage() {}

func (x *MeasurePingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurePingResponse.ProtoReflect.Descriptor instead.
func (*MeasurePingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{5}
}

func (x *MeasurePingResponse) GetResults() []*PingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Delay         int64                  `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{6}
}

func (x *PingResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PingResult) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_ProxyCoreService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyCoreService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_ProxyCoreService_proto_rawDescGZIP(), []int{7}
}

var File_proto_ProxyCoreService_proto protoreflect.FileDescriptor

const file_proto_ProxyCoreService_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ProxyCoreService.proto\x12\tProxyCore\"\xde\x01\n" +
	"\x10StartCoreRequest\x12\x1a\n" +
	"\bcoreName\x18\x01 \x01(\tR\bcoreName\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x1a\n" +
	"\bisString\x18\x05 \x01(\bR\bisString\x12\x1c\n" +
	"\tisVpnMode\x18\x06 \x01(\bR\tisVpnMode\x12\x14\n" +
	"\x05tunFD\x18\a \x01(\rR\x05tunFD\x12\x1c\n" +
	"\tproxyPort\x18\b \x01(\x05R\tproxyPort\"&\n" +
	"\x12MeasurePingRequest\x12\x10\n" +
	"\x03url\x18\x01 \x03(\tR\x03url\"+\n" +
	"\x0fBooleanResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\bR\amessage\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\vLogResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"F\n" +
	"\x13MeasurePingResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.ProxyCore.PingResultR\aresults\"4\n" +
	"\n" +
	"PingResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05delay\x18\x02 \x01(\x03R\x05delay\"\a\n" +
	"\x05Empty2\xa8\x03\n" +
	"\tProxyCore\x12:\n" +
	"\tstartCore\x12\x1b.ProxyCore.StartCoreRequest\x1a\x10.ProxyCore.Empty\x12.\n" +
	"\bstopCore\x12\x10.ProxyCore.Empty\x1a\x10.ProxyCore.Empty\x12=\n" +
	"\risCoreRunning\x12\x10.ProxyCore.Empty\x1a\x1a.ProxyCore.BooleanResponse\x12:\n" +
	"\n" +
	"getVersion\x12\x10.ProxyCore.Empty\x1a\x1a.ProxyCore.VersionResponse\x125\n" +
	"\tfetchLogs\x12\x10.ProxyCore.Empty\x1a\x16.ProxyCore.LogResponse\x12/\n" +
	"\tclearLogs\x12\x10.ProxyCore.Empty\x1a\x10.ProxyCore.Empty\x12L\n" +
	"\vmeasurePing\x12\x1d.ProxyCore.MeasurePingRequest\x1a\x1e.ProxyCore.MeasurePingResponseB\x11Z\x0fproxycoreproto/b\x06proto3"

var (
	file_proto_ProxyCoreService_proto_rawDescOnce sync.Once
	file_proto_ProxyCoreService_proto_rawDescData []byte
)

func file_proto_ProxyCoreService_proto_rawDescGZIP() []byte {
	file_proto_ProxyCoreService_proto_rawDescOnce.Do(func() {
		file_proto_ProxyCoreService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ProxyCoreService_proto_rawDesc), len(file_proto_ProxyCoreService_proto_rawDesc)))
	})
	return file_proto_ProxyCoreService_proto_rawDescData
}

var file_proto_ProxyCoreService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ProxyCoreService_proto_goTypes = []any{
	(*StartCoreRequest)(nil),    // 0: ProxyCore.StartCoreRequest
	(*MeasurePingRequest)(nil),  // 1: ProxyCore.MeasurePingRequest
	(*BooleanResponse)(nil),     // 2: ProxyCore.BooleanResponse
	(*VersionResponse)(nil),     // 3: ProxyCore.VersionResponse
	(*LogResponse)(nil),         // 4: ProxyCore.LogResponse
	(*MeasurePingResponse)(nil), // 5: ProxyCore.MeasurePingResponse
	(*PingResult)(nil),          // 6: ProxyCore.PingResult
	(*Empty)(nil),               // 7: ProxyCore.Empty
}
var file_proto_ProxyCoreService_proto_depIdxs = []int32{
	6, // 0: ProxyCore.MeasurePingResponse.results:type_name -> ProxyCore.PingResult
	0, // 1: ProxyCore.ProxyCore.startCore:input_type -> ProxyCore.StartCoreRequest
	7, // 2: ProxyCore.ProxyCore.stopCore:input_type -> ProxyCore.Empty
	7, // 3: ProxyCore.ProxyCore.isCoreRunning:input_type -> ProxyCore.Empty
	7, // 4: ProxyCore.ProxyCore.getVersion:input_type -> ProxyCore.Empty
	7, // 5: ProxyCore.ProxyCore.fetchLogs:input_type -> ProxyCore.Empty
	7, // 6: ProxyCore.ProxyCore.clearLogs:input_type -> ProxyCore.Empty
	1, // 7: ProxyCore.ProxyCore.measurePing:input_type -> ProxyCore.MeasurePingRequest
	7, // 8: ProxyCore.ProxyCore.startCore:output_type -> ProxyCore.Empty
	7, // 9: ProxyCore.ProxyCore.stopCore:output_type -> ProxyCore.Empty
	2, // 10: ProxyCore.ProxyCore.isCoreRunning:output_type -> ProxyCore.BooleanResponse
	3, // 11: ProxyCore.ProxyCore.getVersion:output_type -> ProxyCore.VersionResponse
	4, // 12: ProxyCore.ProxyCore.fetchLogs:output_type -> ProxyCore.LogResponse
	7, // 13: ProxyCore.ProxyCore.clearLogs:output_type -> ProxyCore.Empty
	5, // 14: ProxyCore.ProxyCore.measurePing:output_type -> ProxyCore.MeasurePingResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ProxyCoreService_proto_init() }
func file_proto_ProxyCoreService_proto_init() {
	if File_proto_ProxyCoreService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ProxyCoreService_proto_rawDesc), len(file_proto_ProxyCoreService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ProxyCoreService_proto_goTypes,
		DependencyIndexes: file_proto_ProxyCoreService_proto_depIdxs,
		MessageInfos:      file_proto_ProxyCoreService_proto_msgTypes,
	}.Build()
	File_proto_ProxyCoreService_proto = out.File
	file_proto_ProxyCoreService_proto_goTypes = nil
	file_proto_ProxyCoreService_proto_depIdxs = nil
}
